import { Article, Feature } from './types';

export const ARTICLES: Article[] = [
  {
    id: 'git-time-machine',
    category: 'Workflow',
    title: 'Git: A Time Machine for Developers',
    description: "Mastering version control is more than just commits; it's about collaborative safety, seamless rollbacks, and the architectural backbone of team-driven software engineering in a global environment.",
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDMQoau5YiiywGYe5n0fJ4F-u-8Uyee4wjBcZBjB7rXACrdAuTWSTFXo7z9jNlaSMRCmUD38nkz46QwfDS8f7_I8WEBmk2yDbKgz6_3UWOhUd_RPNLh57MfKm-88Qq89573hLnQFcN5346Sqjg2Snoz5cc_FSlbEb4VdModMF-XrlL1I5hC3j44ruB45MU4kAxPZabUEIPJTmXI-4V1g7pdv1PbLPAD_C7qrgkUtZSHK7JkzZ8U55pw1VI0V7q7kHK8WG6kSXXAdxa_',
    author: 'Alex Rivers',
    date: 'March 15, 2026',
    content: [
      "Git is more than just a tool; it's a fundamental shift in how we think about software development. In the early days, version control was centralized and fragile. Git changed all that by making every developer's machine a full-fledged repository.",
      "The true power of Git lies in its branching model. Branches are lightweight and encourage experimentation. You can try out a new feature, and if it doesn't work, you can simply discard the branch without affecting the main codebase.",
      "Collaboration is where Git truly shines. Tools like GitHub and GitLab have built entire ecosystems around the pull request workflow, allowing for peer review and automated testing before code ever reaches production.",
    ],
  },
  {
    id: 'ai-superhuman',
    category: 'Future Tech',
    title: 'AI: Replacement or Superhuman?',
    description: "Artificial intelligence isn't coming for your job—it's coming for your repetitive tasks. Learn how to leverage LLMs to augment your productivity and focus on core fundamental logic.",
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBy5Fsx4EMFHRbwuhLCKJtuMLqQqLeLGJB859Klok538cGmm2LjUzsxLxx1lkaUQXEsRJHxOgrjPl8T_IDb7_lyusgxD5nA6wnbbUD8K90Z6-0yq7ydHd-4Y38sE7XxyMBMSwVsMeKLPeR3gu15wH7lYADyA21SO3oBpb08yTKjqsd7wu3rZ71oBnWLnltBAbpslPrbvhUjRijFwNW4Js4REfPIPUCrcfsxz6QpZx42BKAuQgN0VbpQkyUCd6jn1VXZpThqLq3NFcyz',
    author: 'Sarah Chen',
    date: 'March 18, 2026',
    content: [
      "The narrative around AI often swings between utopian dreams and dystopian nightmares. For developers, the reality is much more practical: AI is the ultimate pair programmer.",
      "Large Language Models (LLMs) are exceptionally good at boilerplate, unit tests, and refactoring. By offloading these tasks to AI, developers can spend more time on high-level architecture and solving complex business problems.",
      "The key to thriving in the AI era is 'Prompt Engineering' and critical thinking. AI can generate code, but it's the developer's job to ensure that code is secure, efficient, and fits the overall system design.",
    ],
  },
  {
    id: 'real-world-data-structures',
    category: 'Computer Science',
    title: 'Real-World Data Structures',
    description: 'From the way Google ranks search results to how social media feeds connect you with friends, understanding the core structures behind the software makes you a better architect.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB-H_YEuDl0NiQ9IRQYbltpctrmE_5ezsIcyEEMV_Rl1zL0-xO_GDb6TSWAzwVKHMIi9ws4S9nSw3_x9WbHF5rSNynL7h7agHg5H7vl6PsCtTF4wLEYJpzMh_6o4iY5S8XrLF6xIJCoFR8jGN6ZS_c-glBXzIhCmDwhHyXfnfed66cXX2N9gXcIInyAoStsV9LS0-gi1CN4TsD3007t34d-42QmH2odX0l8V4sDUvfKiW8ZxeE178tDzhpJ6YY09vsEMWMxUiHMqfNW',
    author: 'Marcus Thorne',
    date: 'March 20, 2026',
    content: [
      "Data structures are the building blocks of efficient software. While we often learn about them in abstract terms, their real-world applications are fascinating.",
      "Consider the 'Graph' data structure. It's the foundation of social networks, mapping relationships between millions of users. Or the 'B-Tree', which powers the databases that store almost all of the world's digital information.",
      "Choosing the right data structure is often the difference between a system that scales and one that collapses under its own weight. It's about understanding the trade-offs between time and space complexity.",
    ],
  },
  {
    id: 'digital-resume',
    category: 'Career',
    title: 'Your Digital Resume Beyond CGPA',
    description: 'Your degree is a ticket, but your GitHub is the performance. Build a personal brand that demonstrates curiosity, persistence, and practical problem-solving through open-source contributions.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCKOGY___AaabeqFr3XJxiBPIgWUqjqSEMcc4PV49ywAb6tcA8eyZsjxLWB7PcvMtzVeBdDSoaIOaFdpelcZnVrvS9c-uDUyqOr8d1f8BTNcbqBBQxbuDccjGlO8T7eFwdwyaN4_M_Sd41VPacBcd8-HDDVKyhw6GypJyHPcKU6XUYM6bCJkK-J_6OlI2ZIhVQYDhIQpkd9NG3UMNaI1SLLDSM--okGuBdIl0y8CQe5EO9vaB7YKNSrKEqIlDgPjMhQCHFGVzjKp99H',
    author: 'Elena Vance',
    date: 'March 22, 2026',
    content: [
      "In today's competitive job market, a degree is just the baseline. Employers are looking for proof of skill, and there's no better proof than a public track record of contributions.",
      "Open source is the ultimate equalizer. It doesn't matter where you went to school; what matters is the quality of your code and your ability to collaborate with others.",
      "Start small. Fix a typo in a README, or solve a minor bug in a library you use. Over time, these small contributions build into a portfolio that speaks louder than any resume.",
    ],
  },
  {
    id: 'writing-code-for-humans',
    category: 'Craftsmanship',
    title: 'Writing Code for Humans',
    description: 'Computers execute instructions; humans maintain systems. Learn the art of Clean Code, intentional naming, and building software that welcomes future developers rather than scaring them.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAfeGDY8DHmpoohxgcGw0hNI9m9ppTrpUbverJHONKsOoLPtpL2eEW1nu-e-ZOVvsAnDZ_gUCCfTEd1KQol_7hUV1c5U1k3TkyQeTy8M3SZmFk9Dg60kKjwkiFQVA1UXVZz84uSje-sQXxk30izj7VFEC9Fov0cqI4riqXT0xnhwp5ZZXG8hvHUno2GEHGOly5lI5jxV35B74jGuVKzFNjBx40KnxfV3hQVbrgZxPa0YiHkmlb72kKiHIQSKV9wXYqwfgt5Ous23hre',
    author: 'Robert Martin',
    date: 'March 23, 2026',
    content: [
      "The best code isn't the most clever; it's the most readable. We spend far more time reading code than writing it, so we should optimize for the reader.",
      "Clean code is about intent. When you name a variable or a function, you're telling a story. If that story is clear, the system is easy to maintain. If it's muddled, technical debt accumulates.",
      "Refactoring is a continuous process. Don't wait for a 'cleanup day' that will never come. Leave the campground cleaner than you found it, one commit at a time.",
    ],
  },
  {
    id: 'rise-of-no-code',
    category: 'Emerging Trends',
    title: 'The Rise of No-Code Tools',
    description: 'Is it a threat or a tool? Discover how professional developers are using no-code for rapid prototyping and internal tools to save time for more complex architectural challenges.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBGExIFXkn_QDpSZbKWSbtW9lt76Y2ruK0PlXNd-34zUU1TjOYttrKd80TDuvLijVpy2uBNMpXtiETOADZ50IKOCGY8dfqhWZfZtaYlbGr8fq7F-H6Y5esuVnHTVF8CW4rbo9v_ww0-TFjs-KlEUD6SRYe1N4jo8PO5iRC6sdBJJ5IDuhr0I95fEsc_Or04zbqB2EJBBrPU9B6E6AsKKstJo5qicNW_V2lv4L7Lm-775uxjcMoJJw7gs2v_nm_t0UqybUbGwj_UPVXC',
    author: 'Jordan Smith',
    date: 'March 24, 2026',
    content: [
      "No-code tools are often dismissed by 'real' developers, but that's a mistake. These tools are powerful allies for rapid prototyping and building internal utilities.",
      "By using no-code for the simple stuff, developers can focus their energy on the unique, complex logic that defines their product. It's about efficiency and choosing the right tool for the job.",
      "The future of development is hybrid. We'll use high-level visual tools for the interface and low-level code for the performance-critical core. The boundaries are blurring.",
    ],
  },
  {
    id: 'soft-skills-hardcore-coders',
    category: 'Professionalism',
    title: 'Soft Skills for Hardcore Coders',
    description: 'Communication, empathy, and problem-solving are the true 10x developer traits. Learn why your ability to explain a concept matters just as much as your ability to code it.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA9GGiWzDHa8zLTTfckOryp3oIAmH21MWYBkVlh16mtYoPkJ8_XvXycklsBEsm1RDQ4Bwf1gK0UC0lM7_AH51W_zRN_TEZ4c6ZNv_avZEqBIEV-KD6VklFZPrYwRZbhG1WHj0AXdd5PalwLC3FtOijjKJrPqW2_6n80WF6Z94rYU1AP5vkGAiiZa905jJxnGZ_hEwE_-jYyUKykCRtXvC8vMbK5NAuohWhUIw2DfZCKi5CGo864mjyNlf86L38RGYUcBLsLa1Qojy-h',
    author: 'David Heinemeier',
    date: 'March 24, 2026',
    content: [
      "Software development is a team sport. No matter how good you are at coding, your impact is limited if you can't communicate effectively with your teammates and stakeholders.",
      "Empathy is a superpower. When you understand the problems your users are facing, you build better solutions. When you understand the challenges your teammates are dealing with, you build a better team.",
      "The '10x developer' isn't just someone who writes 10x more code; it's someone who makes everyone around them 10x better through clear communication and mentorship.",
    ],
  },
  {
    id: 'digital-hygiene',
    category: 'Security',
    title: 'Digital Hygiene & Cybersecurity',
    description: "Security is everyone's responsibility. Master the basics of 2FA, phishing defense, and secure coding practices to protect both your data and your users' privacy in 2026.",
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuByKM6adJxfO3-WlJ2LbOwubw29VeVjUrjq0-tICWSZLPx_fRyGKoCl9da7PBPCi_hWxu-mLaZVy9JXW7gtDe5BJMvB9m3f4YkGWAvAR864vsQUOOv_Sy8TjQm3bO4aXcq0is_mMFLcOReA5CQzEx5SYmP9xXIkekP7gZJ_UQcHfXwa-5ph2L0_bIclmeJuKNKSSlcGRyWzZPRDGB8Wl6rGgneNiTbRfdptKKLnNMr1508KpKsB84VwTREeEyEiSk0xCET9UoTkX4R-',
    author: 'Kevin Mitnick',
    date: 'March 24, 2026',
    content: [
      "In 2026, security is no longer an afterthought; it's a core requirement. The threats are more sophisticated, but the basics of digital hygiene still go a long way.",
      "Two-factor authentication (2FA) is non-negotiable. Password managers are essential. But beyond tools, it's about awareness. Most breaches start with a simple phishing email.",
      "Secure coding means thinking like an attacker. Validate every input, sanitize every output, and never trust the client. Security is a mindset, not a checklist.",
    ],
  },
];

export const FEATURES: Feature[] = [
  {
    id: 'speed',
    title: 'Extreme Speed',
    description: 'Rapid iteration cycles and efficient workflows are no longer optional—they are the minimum requirement for competitive development.',
    icon: 'Zap',
    bgColor: 'bg-primary-fixed',
    iconColor: 'text-primary',
  },
  {
    id: 'security',
    title: 'Unmatched Security',
    description: 'As attacks become more automated, a "security-first" mindset in code architecture is the only way to build trust and longevity.',
    icon: 'ShieldCheck',
    bgColor: 'bg-secondary-fixed',
    iconColor: 'text-secondary',
  },
  {
    id: 'scalability',
    title: 'Infinite Scalability',
    description: 'Writing code that can grow from ten users to ten million requires deep understanding of patterns and resource management.',
    icon: 'Compass',
    bgColor: 'bg-tertiary-fixed',
    iconColor: 'text-tertiary',
  },
];
